#!/bin/bash

# Create .env file
echo "MONGO_URI=$MONGO_URI" > .env
echo "MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE" >> .env
echo "MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME" >> .env
echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD" >> .env
echo "BCRYPT_SALT=$BCRYPT_SALT" >> .env
echo "JWT_SECRET=$JWT_SECRET" >> .env
echo "PUBLIC_URL=$PUBLIC_URL" >> .env
echo "NOTCHPAY_PK=$NOTCHPAY_PK" >> .env
echo "NOTCHPAY_SK=$NOTCHPAY_SK" >> .env
echo "META_MESSAGING_API_BASE_URL=$META_MESSAGING_API_BASE_URL" >> .env
echo "META_MESSAGING_API_ACCESS_TOKEN=$META_MESSAGING_API_ACCESS_TOKEN" >> .env
echo "GEOAPIFY_KEY=$GEOAPIFY_KEY" >> .env
echo "ADMIN_EMAIL=$ADMIN_EMAIL" >> .env
echo "ADMIN_PHONE_NUMBER=$ADMIN_PHONE_NUMBER" >> .env
echo "ADMIN_PASSWORD=$ADMIN_PASSWORD" >> .env
echo "REGISTRY_USERNAME=$REGISTRY_USERNAME">> .env
echo "CONTAINER_REGISTRY=$CONTAINER_REGISTRY">> .env
echo "REGISTRY_PASSWORD=$REGISTRY_PASSWORD">> .env