# docker-compose.yml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/hublots/hublots-api:latest
    container_name: hublots_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    networks:
      - mongo-cluster_mongo-cluster

networks:
  mongo-cluster_mongo-cluster:
    external: true
